### ISSUE TITLE
DELETE to /v1/users/usr_blah doesn't.

### ISSUE THREAD

**Issue by tomoconnor** [lunoio/luno-node#1]
Based on the example:
[luno_test.js.txt](https://github.com/lunoio/luno-node/files/194408/luno_test.js.txt)

It looks like the API side of the DELETE verb on /users/ doesn't expect the version parameter that's actually returned as part of the output from GET /users/.. 

```
Found user Osborne.Schiller67
URL:  /v1/users/usr_dQWGpqhDvD0gua

Running:
        luno.delete(element.url, {permanent: true}, function(err, resp) {

Gives:
{ [Error: Route not found]
  code: 'route_not_found',
  description: 'This API route wasn\'t found, please see https://luno.io/docs to see valid routes.',
  status: 404,
  extra: undefined }

But:
        luno.delete('/users/' + element.id , {permanent: true}, function(err, resp) {

Works.
Deleted Osborne.Schiller67
```

**Comment by simontabor** [comment]
@tomoconnor got it, the API returns URLs with the `/v1` prefix but the library doesn't like that. I'll make it so that it works either way (with or without `v1`).

Thanks for the report!
